openapi: 3.0.3

info:
  title: Recipe API
  version: 1.0.0
  description: API for add, delete, fetch, and search recipes

servers:
  - url: https://{host}
    variables:
      host:
        default: demo.recipe.com
        enum:
          - demo.recipe.com
          - localhost

paths:

  /api/rest/recipe:
    post:
      summary: adds a new recipe
      tags:
        - AddRecipe
      operationId: add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schema/recipe/add/AddRecipeRequest.yaml'
      responses:
        '201':
          description: newly added recipe
          content:
            application/json:
              schema:
                $ref: './schema/recipe/add/AddRecipeResponse.yaml'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '401':
          description: unauthorized (token missing or invalid)
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'

  /api/rest/recipe/{recipeId}:
    delete:
      summary: deletes a recipe
      tags:
        - DeleteRecipe
      operationId: delete
      parameters:
        - in: path
          name: recipeId
          schema:
            type: string
            format: uuid
          required: true
          description: recipe identifier
      responses:
        '204':
          description: recipe was deleted successfully
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '401':
          description: unauthorized (token missing or invalid)
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'

    get:
      summary: retrieves a recipe
      tags:
        - RetrieveRecipe
      operationId: retrieve
      parameters:
        - in: path
          name: recipeId
          schema:
            type: string
            format: uuid
          required: true
          description: recipe identifier
      responses:
        '200':
          description: recipe was retrieved successfully
          content:
            application/json:
              schema:
                $ref: './schema/recipe/retrieve/RetrieveRecipeResponse.yaml'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '401':
          description: unauthorized (token missing or invalid)
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'

  /api/rest/recipe/search:

    post:
      summary: retrieves a list of recipes based on given criteria
      tags:
        - RetrieveRecipe
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schema/recipe/search/SearchRecipeRequest.yaml'
      responses:
        '200':
          description: recipe list was retrieved successfully
          content:
            application/json:
              schema:
                $ref: './schema/recipe/search/SearchRecipeResponse.yaml'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '401':
          description: unauthorized (token missing or invalid)
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: './schema/generic/ErrorResponse.yaml'